services:
  - type: web
    name: nigra-backend
    env: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://mimo.uy
      - key: BASE_URL
        value: https://mimo.uy
